services:
  postgres:
    image: postgres:latest
    container_name: postgres-bobscorn
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
  
  redis:
    image: redis:latest
    container_name: redis-bobscorn
    ports:
      - "6379:6379"
